export * from './Upload';
export * from './Plus';
export * from './Pencil';
export * from './Trash';
export * from './Award';
export * from './Users';
export * from './LogOut';
export * from './MessageSquare';
// Re-export existing icons
export * from '../icons';